### ISSUE TITLE
Latest release shows v0.1.1 not v0.2.0

### ISSUE THREAD

**Issue by maresb** [repo-helper/hatch-requirements-txt#18]
![image](https://user-images.githubusercontent.com/15216687/194678620-059df28e-adc9-4b54-bdc3-d13765d1a795.png)

**Comment by domdfcoding** [comment]
There's [a bot](https://github.com/domdfcoding/octocheese) that runs at 2PM which does the conversion from Git tag to GitHub release. I've run it manually in any case so the release should be there now.
