### ISSUE TITLE
Won't read files generated by pip-compile

### ISSUE THREAD

**Issue by bigjools** [repo-helper/hatch-requirements-txt#34]
## Description

I have requirements files generated by pip-tools' compiler, which include index URLS, hashes and `\` line wrap markers. The `packaging` module used by `hatch-requirements-txt` won't read these.

## Steps to Reproduce

Example file:
```
alembic==1.9.1 \
    --hash=sha256:a9781ed0979a20341c2cbb56bd22bd8db4fc1913f955e705444bd3a97c59fa32 \
    --hash=sha256:f9f76e41061f5ebe27d4fe92600df9dd612521a7683f904dab328ba02cffa5a2
```

## Actual result:

The tail end of the traceback:
```
  File "/home/juledwar/.local/share/hatch/env/virtual/helios/mzodncRb/helios-build/lib/python3.10/site-packages/hatch_requirements_txt/__init__.py", line 65, in parse_requirements
    req = Requirement(line)
  File "/home/juledwar/.local/share/hatch/env/virtual/helios/mzodncRb/helios-build/lib/python3.10/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    alembic==1.9.1 \
```

## Expected result:
A parsed requirements file.

## Reproduces how often:

Trivially.

## Version

  * Operating System: Linux
  * Python: 3.10
  * hatch-requirements-txt: latest

## Installation source

pypi

## Other Additional Information:

If there's a `--index` at the top of the file (a valid `pip` directive) it also fails to parse.

It seems like there's a large gap between what pip can use and what this project can handle.

**Comment by domdfcoding** [comment]
Can you give the [pip-compile](https://github.com/repo-helper/hatch-requirements-txt/tree/pip-compile branch a try?

I've made it ignore the `--` commands entirely, since they're only valid when passed to pip directly and not as dependencies of a wheel.

You should be able to use the following in `pyproject.toml` to have that branch installed directly from GitHub when you build your project:

```toml
[build-system]
requires = ["hatch-requirements-txt@https://github.com/repo-helper/hatch-requirements-txt/archive/pip-compile.zip"]
build-backend = "hatchling.build"
```

If it works for you I'll make a new release.

**Comment by bigjools** [comment]
Thanks for looking at this quickly! Unfortunately I've deleted my original config and use of this since I was doing things incorrectly anyway (making bad assumptions about how Hatch was working with deps). However, I might advise that if you can flag up the use of `--` commands as an error unless explicitly ignored, it would be better. Some people might throw those at the new code and assume it's hash checking, when it's not.

Cheers.
