### ISSUE TITLE
Support for features / optional dependencies

### ISSUE THREAD

**Issue by ofek** [repo-helper/hatch-requirements-txt#6]
Hey, great plugin!

For example this https://github.com/aws/sagemaker-python-sdk/blob/49c664893339b42815b2fe8a91d912194199e8ba/setup.py#L64-L72 might become:

```toml
[tool.hatch.metadata.hooks.requirements_txt.features]
local = ["requirements/extras/local_requirements.txt"]
scipy = ["requirements/extras/scipy_requirements.txt"]
all = [
  "requirements/extras/local_requirements.txt",
  "requirements/extras/scipy_requirements.txt",
]
test = [
  "requirements/extras/local_requirements.txt",
  "requirements/extras/scipy_requirements.txt",
  "requirements/extras/test_requirements.txt",
]
```

& maybe the top-level option should become an array too?

```toml
[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]
```

**Comment by maresb** [comment]
@ofek, I attempted an implementation in #13. However I don't understand why you suggest above calling the replacement `optional-dependencies` section `features`. According to my tastes, it introduces redundant and confusing terminology, but on the other hand, you tend to have good reasons for your design decisions. :smile: Which name shall we use?

**Comment by ofek** [comment]
oh awesome! it's up to you, Hatch refers to them as [features](https://hatch.pypa.io/latest/config/environment/overview/#features) b/c it's easier to type/remember and it matches https://doc.rust-lang.org/cargo/reference/features.html

**Comment by maresb** [comment]
Great, thanks for the context! I'd prefer to keep `optional-dependencies`, but I added that groups of optional dependencies are "also known as "features"" in the README.
